"use client";
import React from "react";
export default function Home() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-900 to-blue-900 text-white p-8">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-12">
          <h1 className="text-5xl font-bold mb-4">Dev AI</h1>
          <p className="text-xl text-blue-200">
            AI-Generated Production System
          </p>
        </div>
        <div className="grid md:grid-cols-2 gap-6">
          <div className="bg-white/10 rounded-xl p-6">
            <h2 className="text-2xl font-bold mb-4">System Overview</h2>
            <p className="text-blue-100">
              This system was automatically generated by Dev AI
              from a Business Requirements Document (BRD).
            </p>
          </div>
          <div className="bg-white/10 rounded-xl p-6">
            <h2 className="text-2xl font-bold mb-4">Built With</h2>
            <ul className="text-blue-100 space-y-2">
              <li>✓ Next.js 14</li>
              <li>✓ TypeScript</li>
              <li>✓ Tailwind CSS</li>
              <li>✓ Supabase</li>
            </ul>
          </div>
        </div>
      </div>
    </main>
  );
}
