"use client";
import React from "react";
export default function Home() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-900 to-blue-900 text-white p-8">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-12">
          <h1 className="text-5xl font-bold mb-4">Dev AI</h1>
          <p className="text-xl text-blue-200">AI-Generated Production System</p>
        </div>
        <div className="mb-12">
          <h2 className="text-2xl font-bold mb-6">Features</h2>
          <div className="grid md:grid-cols-2 gap-4">
            <a href="/dev-engine" className="block bg-white/10 hover:bg-white/20 transition rounded-xl p-6">\n              <h3 className="text-xl font-semibold mb-2">Dev engine</h3>\n              <p className="text-blue-200 text-sm">Navigate to /dev-engine</p>\n            </a>\n            <a href="/workflow" className="block bg-white/10 hover:bg-white/20 transition rounded-xl p-6">\n              <h3 className="text-xl font-semibold mb-2">Workflow</h3>\n              <p className="text-blue-200 text-sm">Navigate to /workflow</p>\n            </a>\n            <a href="/standards" className="block bg-white/10 hover:bg-white/20 transition rounded-xl p-6">\n              <h3 className="text-xl font-semibold mb-2">Standards</h3>\n              <p className="text-blue-200 text-sm">Navigate to /standards</p>\n            </a>\n            <a href="/agents" className="block bg-white/10 hover:bg-white/20 transition rounded-xl p-6">\n              <h3 className="text-xl font-semibold mb-2">Agents</h3>\n              <p className="text-blue-200 text-sm">Navigate to /agents</p>\n            </a>\n            <a href="/platform-expansion" className="block bg-white/10 hover:bg-white/20 transition rounded-xl p-6">\n              <h3 className="text-xl font-semibold mb-2">Platform expansion</h3>\n              <p className="text-blue-200 text-sm">Navigate to /platform-expansion</p>\n            </a>
          </div>
        </div>
        <div className="grid md:grid-cols-2 gap-6">
          <div className="bg-white/10 rounded-xl p-6">
            <h2 className="text-2xl font-bold mb-4">System Overview</h2>
            <p className="text-blue-100">This system was automatically generated by Dev AI from a Business Requirements Document (BRD).</p>
          </div>
          <div className="bg-white/10 rounded-xl p-6">
            <h2 className="text-2xl font-bold mb-4">Built With</h2>
            <ul className="text-blue-100 space-y-2">
              <li>Next.js 14</li>
              <li>TypeScript</li>
              <li>Tailwind CSS</li>
            </ul>
          </div>
        </div>
      </div>
    </main>
  );
}
